# Inserts a blank line between shell prompts
add_newline = false

format = """
$cmd_duration\
$username\
$hostname\
$directory\
$shlvl\
$kubernetes\
$vcsh\
$git_status\
$git_branch\
$git_commit\
$git_state\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$direnv\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[character]
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
format = "◷ [$duration]($style) \n"

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 1

[direnv]
disabled = false

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""
truncation_length = 28

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
conflicted = '[!$count](red)'
untracked = '[?$count](cyan)'
modified = '[*$count](red)'
staged = '[+$count](green)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[ruby]
format = 'rb:[$symbol($version )]($style) '
symbol = ""

[nodejs]
format = 'js:[$symbol($version )]($style) '
symbol = ""

[hostname]
ssh_only = true
format = "[$hostname]($style) "

[username]
format = "[$user]($style)@"
show_always = false

[kubernetes]
disabled = true

# Disabled modules
[aws]
disabled = true

[gcloud]
disabled = true

[golang]
format = 'go:[$symbol($version )]($style) '
symbol = ""

[rust]
format = 'rs:[$symbol($version )]($style) '
symbol = ""

[docker_context]
disabled = true
